# Generated by Django 5.2.7 on 2026-05-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0005_registro_processado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('solicitante', models.CharField(max_length=200)),
                ('projeto', models.CharField(max_length=250)),
                ('sistema', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EstimativaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('modulo_processo', models.CharField(blank=True, max_length=200)),
                ('recurso', models.CharField(blank=True, max_length=200)),
                ('escopo', models.TextField()),
                ('horas_analise', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horas_atividade', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horas_gp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='horas.estimativa')),
            ],
            options={
                'ordering': ['ordem', 'pk'],
            },
        ),
    ]
