# Generated by Django 5.2.7 on 2026-05-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('horas', 'UserProfile')

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0006_estimativa_estimativaitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gerente_projetos', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AgendaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('numero_chamado', models.CharField(blank=True, max_length=100)),
                ('produto', models.CharField(blank=True, max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_atividades_criadas', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_atividades', to='horas.orcamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_inicio', 'titulo', 'pk'],
            },
        ),
    ]
