# Generated by Django 5.2.7 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0007_userprofile_agendaatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaatividade',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendaatividade',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendaatividade',
            name='total_horas_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterModelOptions(
            name='agendaatividade',
            options={'ordering': ['data_inicio', 'hora_inicio', 'titulo', 'pk']},
        ),
    ]
