# Generated by Django 5.2.7 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0008_agendaatividade_horarios_total_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='numero_chamado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
