# Generated by Django 5.2.7 on 2026-06-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0009_orcamento_codigo_cliente_numero_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Informe somente números.',
                        regex='^\\d+$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo_cliente',
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Informe somente números.',
                        regex='^\\d+$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='numero_chamado',
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Informe somente números.',
                        regex='^\\d+$',
                    )
                ],
            ),
        ),
    ]
