# Generated by Django 5.2.7 on 2026-06-15

from datetime import datetime, timedelta
from decimal import Decimal

from django.db import migrations, models


def preencher_horas_apontadas(apps, schema_editor):
    Orcamento = apps.get_model('horas', 'Orcamento')
    Registro = apps.get_model('horas', 'Registro')

    totais = {}
    for registro in Registro.objects.all().iterator():
        inicio = datetime.combine(datetime.min, registro.hora_inicio)
        fim = datetime.combine(datetime.min, registro.hora_fim)
        delta = fim - inicio
        if delta.days < 0:
            delta += timedelta(days=1)
        total = Decimal(delta.total_seconds()) / Decimal('3600')
        totais[registro.orcamento_id] = totais.get(registro.orcamento_id, Decimal('0')) + total

    for orcamento_id, total in totais.items():
        Orcamento.objects.filter(pk=orcamento_id).update(horas_apontadas=total)


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0011_orcamento_horas_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='horas_apontadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.RunPython(preencher_horas_apontadas, migrations.RunPython.noop),
    ]
