# Generated by Django 5.2.7 on 2026-06-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0012_orcamento_horas_apontadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='horas_adicionais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='SolicitacaoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_horas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('motivo', models.TextField()),
                ('situacao', models.CharField(choices=[('AGUARDANDO', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='AGUARDANDO', max_length=10)),
                ('motivo_reprovacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_horas_decididas', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_horas', to='horas.orcamento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
