# Generated by Django 5.2.7 on 2026-07-09 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def consolidar_folgas_para_todos(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    FolgaFeriado = apps.get_model('horas', 'FolgaFeriado')
    total_usuarios = User.objects.count()
    if not total_usuarios:
        return

    grupos = (
        FolgaFeriado.objects.filter(abrangencia_todos=False, user__isnull=False)
        .values('criado_por_id', 'data', 'descricao')
        .annotate(total_usuarios=Count('user', distinct=True))
        .filter(total_usuarios=total_usuarios)
    )
    for grupo in grupos:
        registros = FolgaFeriado.objects.filter(
            abrangencia_todos=False,
            user__isnull=False,
            criado_por_id=grupo['criado_por_id'],
            data=grupo['data'],
            descricao=grupo['descricao'],
        ).order_by('pk')
        principal = registros.first()
        if not principal:
            continue
        registros.exclude(pk=principal.pk).delete()
        principal.user = None
        principal.abrangencia_todos = True
        principal.save(update_fields=['user', 'abrangencia_todos'])

class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0022_folgaferiado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folgaferiado',
            options={'ordering': ['-data', '-abrangencia_todos', 'user__username', 'pk']},
        ),
        migrations.AddField(
            model_name='folgaferiado',
            name='abrangencia_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folgaferiado',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folgas_feriados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(consolidar_folgas_para_todos, migrations.RunPython.noop),
    ]
