# Generated by Django 5.2.7 on 2026-07-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0023_alter_folgaferiado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
    ]
