# Generated by Django 5.2.7 on 2026-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0024_userprofile_is_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaatividade',
            name='destino_para',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('TERCEIRO', 'Terceiro')], default='INTERNO', max_length=20),
        ),
        migrations.AddField(
            model_name='agendaatividade',
            name='quantidade_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
