# Generated by Django 5.2.7 on 2026-08-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0027_configuracaosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_vinculados', to='horas.orcamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_vinculados', to='horas.servico')),
            ],
            options={
                'ordering': ['orcamento__codigo', 'servico__codigo'],
                'unique_together': {('orcamento', 'servico')},
            },
        ),
    ]
