# Generated by Django 5.2.7 on 2026-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0028_orcamentoservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='envia_erp',
            field=models.BooleanField(default=False, verbose_name='Envia ERP'),
        ),
    ]
